name: Deploy Blazor WASM to GitHub Pages

on:
  workflow_dispatch:  # Trigger workflow manuelt

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸ“¥ Checkout repo
      uses: actions/checkout@v4

    - name: ğŸ§° Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: ğŸ›  Restore
      run: dotnet restore

    - name: ğŸ— Build
      run: dotnet build --configuration Release

    - name: ğŸš€ Publish
      run: dotnet publish CSStatsTracker/CSStatsTracker.csproj -c Release -o build_output

    - name: ğŸ“„ Add .nojekyll
      run: touch build_output/wwwroot/.nojekyll

    - name: ğŸšš Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build_output/wwwroot
        publish_branch: gh-pages
